### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'Conj' and 'Form'

### ISSUE THREAD

**Issue by PBouteiller** [FEniCS/ufl#103]
Hi i have met a very basic bug, or at least a strange behaviour, involving ufl

Here is a very minimal code showing the issue:

```python
from dolfin import *

mesh = RectangleMesh(Point(0., 0.), Point(1, 1), 1, 1, "crossed")
V = VectorFunctionSpace(mesh, 'CG', degree=2)
u_ = TestFunction(V)
x = SpatialCoordinate(mesh)
```

Working

```python
first_form = inner(Constant((1,1)), u_) * x[0] * dx
print("First form", first_form)
```

Not working

```python
dx1 = x[0] * dx
second_form = inner(Constant((1,1)), u_) * dx1
print("Second form", second_form)
```

No operation is defined between the Conj operator and a ufl-form even though one could expect these two syntax to be equivalent

**Comment by mscroggs** [comment]
These two expressions are not equivalent. The first example multiples `inner(Constant((1,1)), u_)` and `x[0]` first to form an expression, then multiplies this by `dx`. The latter multiplies `x[0]` and `dx` first to get a form. This then cannot be multiplied by an expression.
