### ISSUE TITLE
ufl 2023.1 breaks old dolfin

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/ufl#151]
The change of API in ufl 2023.1 (2023.1.1.post0) breaks old dolfin.

It also breaks old ffc.  `ufl.log.WARNING` was removed in ufl 2023 and is used by ffc. But ffc can be easily patched to treat any instance of WARNING as either INFO or ERROR.

dolfin cannot be so easily patched. The problem is not only ufl.log.WARNING. For instance demo_poisson.py gives
```
$ python3 demo_poisson.py 
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Traceback (most recent call last):
  File "/projects/fenics/build/tests/dolfin/demo-python/documented/poisson/demo_poisson.py", line 170, in <module>
    solve(a == L, u, bc)
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfin/fem/solving.py", line 233, in solve
    _solve_varproblem(*args, **kwargs)
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfin/fem/solving.py", line 268, in _solve_varproblem
    problem = LinearVariationalProblem(eq.lhs, eq.rhs, u, bcs,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfin/fem/problem.py", line 58, in __init__
    L = Form(L, form_compiler_parameters=form_compiler_parameters)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/petsc/lib/python3/dist-packages/dolfin/fem/form.py", line 82, in __init__
    self.set_cell_domains(subdomains)
TypeError: set_cell_domains(): incompatible function arguments. The following argument types are supported:
    1. (self: dolfin.cpp.fem.Form, arg0: dolfin.cpp.mesh.MeshFunctionSizet) -> None

Invoked with: <dolfin.fem.form.Form object at 0x7f67280289b0>, [None]
```

Should ufl be patched (as version 2023.2, say) to restore support for old dolfin?

Or should the new namespace be changed from ufl to uflx ?  This was done previously when ffc was changed to ffcx

**Comment by drew-parsons** [comment]
Note that old dolfin has already been patched to work successfully with ufl 2022.2.0.  This error is new in ufl 2023.

**Comment by dham** [comment]
I'm not really keen on arbitrarily changing the name of UFL. Can we not just point old dolfin at an old version?

**Comment by dham** [comment]
Using package names for versioning doesn't sound very sustainable. So if we want to make Firedrake Ubuntu packages then (given that Firedrake and FEniCS UFL can be out of sync) we also need another name there? This sounds like a mess.

**Comment by drew-parsons** [comment]
Well there can be different packages available that conflict with each other, where either one or the other can be installed at one time.  But what I want to facilitate is the capability to support running different research projects on the same computer, one using dolfin, another using dolfix (or firedrake). That means simultaneous installation of the packages, i.e. with a common ufl, or with some renaming of ufl.

**Comment by dham** [comment]
OK so the options that technically work are:

1. patch UFL.
2. rename old UFL
3. rename new UFL

1 Is going to get increasingly difficult because SysGenX intends to make backwards incompatible UFL changes. So we need to do 2 or 3. Given the brand name that UFL has, I am not keen to change the name of the current version, though others may have other opinions. Maybe we should change the old version to e.g. ufl2022 and just patch the old packages (e.g. `import ufl2022 as ufl`)

**Comment by drew-parsons** [comment]
Any of those options resolves the issue for me. Either of options two or three cause some application code disruption, but the disruption is not huge, e.g only requires replacing `import ufl` with `import ufl2022 as ufl` as you suggested.

If option 2 is judged the preferred option, then renaming as ufl_legacy is another possibility. ufl_legacy is more "expressive" (i.e. communicates to stop using it if possible), while ufl2022 is more "informative" (indicates precisely what it is).

**Comment by mscroggs** [comment]
I like possibility 2 with the name ufl_legacy. I think @jorgensd posted somewhere else which ufl release was the last one that worked with old dolfin, so we should package that version up

**Comment by drew-parsons** [comment]
old dolfin has been patched to work with ufl 2022, so dham's ufl2022 would be fine for legacy dolfin.

**Comment by jhale** [comment]
ufl_legacy would be better than ufl2022, leaving open the possibility that it is updated/fixed in the future. In any case, option 2 seems like a good compromise.

**Comment by drew-parsons** [comment]
I opened a draft PR started in #155 .  I have an implementation question, I'll raise it there
