### ISSUE TITLE
H1curl matrix element get bigger and bigger

### ISSUE THREAD

**Issue by wwshunan** [FEniCS/ufl#16]
Hi all, I found the maximum element value of the assemble matrix of inner(curl(u), curl(v))*dx increases with the mesh size, while inner(u, v)*dx does not. Is it normal?

from fenics import *

mesh = UnitSquareMesh(40, 40)
V = FunctionSpace(mesh, "N1curl", 1)

u = TrialFunction(V)
v = TestFunction(V)
a = inner(curl(u), curl(v)) * dx
A = assemble(a)

A.array().max()

**Comment by garth-wells** [comment]
Use https://fenicsproject.discourse.group/ for general questions.
