### ISSUE TITLE
importing a submodule import the whole of ufl

### ISSUE THREAD

**Issue by mscroggs** [FEniCS/ufl#164]
Currently the following code runs without error. It shouldn't.

```python
import ufl.utils

print(ufl.dx())
```

**Comment by francesco-ballarin** [comment]
The same issue should be probably opened in almost every repository, for instance
```
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dolfinx.fem
>>> dolfinx.mesh
<module 'dolfinx.mesh' from '[...]/site-packages/dolfinx/mesh.py'>
```

**Comment by mscroggs** [comment]
Ah right, looks like this is a Python quirk I was unaware of and not UFL specific

**Comment by wence-** [comment]
Yes, importing a submodule is explicitly designed as importing all parent packages.
