### ISSUE TITLE
`typing_extensions` breaks Spack build

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/ufl#174]
See https://github.com/FEniCS/dolfinx/actions/runs/5407842569/jobs/9826291336.

Is it essential?

**Comment by wence-** [comment]
I suppose not, it's a backport package for new type annotation features to older python versions. Is this happening because the spack build doesn't install requirements in the same way?

**Comment by garth-wells** [comment]
Dependencies need to be listed explicitly with Spack, see https://spack.readthedocs.io/en/2021.08.19/build_systems/pythonpackage.html#python-dependencies for the reasons.

**Comment by garth-wells** [comment]
`typing_extensions` is used to type hint very few 'private' methods, probably not justifying the introduction of a dependency. Easiest would be to remove. Docs can explain the type.
