### ISSUE TITLE
Release ufl_legacy

### ISSUE THREAD

**Issue by minrk** [FEniCS/ufl#191]
Now that there are releases of dolfin-adjoint and support in the main branch of other packages for ufl_legacy, it seems appropriate to publish a release of ufl_legacy.

This presumably involves:

1. tagging the latest commit on the ufl_legacy branch (e.g. `ufl_legacy-2022.3.0` to match the version in the metadata)
2. publishing to PyPI by running the [build-wheels workflow](https://github.com/FEniCS/ufl/actions/workflows/build-wheels.yml)

The wheels workflow _may_ work, depending on the credentials given to the workflow. If it's a scoped token that only has permission to publish ufl releases, then it will fail to upload and someone can manually upload and register with twine. GitHub [environment secrets](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) can be used to separate credentials for ufl_legacy, or setting it up as a [trusted publisher](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/) so no credentials need to be managed.

**Comment by mscroggs** [comment]
New release of fenics-ufl-legacy: https://pypi.org/project/fenics-ufl-legacy/2022.3.0/
