### ISSUE TITLE
`pow` is not available

### ISSUE THREAD

**Issue by Noahyt** [FEniCS/ufl#23]
I would like to do something like `a = ufl.pow(b, 2)`. This returns `module 'ufl' has no attribute 'pow'`. However I can implement the desired functionality using `b ** 2`

This may be merely a problem with documentation. I see it listed under "basic nonlinear functions" here https://fenics.readthedocs.io/projects/ufl/en/latest/manual/form_language.html?highlight=square#basic-nonlinear-functions

Thank you!

**Comment by hermanmakhm** [comment]
It doesn't seem this was actually resolved when it was closed. The [documentation that's labelled "latest"](https://fenics.readthedocs.io/projects/ufl/en/latest/manual/form_language.html) does not match [UFL's source code.](https://github.com/FEniCS/ufl/blob/main/ufl/algebra.py)

**Comment by lclaire** [comment]
I am running into this issue today: "module 'ufl' has no attribute 'pow'"

**Comment by jorgensd** [comment]
> I am running into this issue today: "module 'ufl' has no attribute 'pow'"

`ufl` doesn't how a pow object as `pow` is built-in in Python (similar to +, -, / and **).
Just use `pow(a, b)` without loading `pow` from any library.

**Comment by lclaire** [comment]
ok, ufl documentation is outdated then? https://fenics.readthedocs.io/projects/ufl/en/latest/manual/form_language.html 
![Screenshot from 2024-05-14 10-54-01](https://github.com/FEniCS/ufl/assets/60707917/d4a4d7dc-918d-44df-a475-cec5c97d04ca)

**Comment by jorgensd** [comment]
I guess the documentation could be imporved, as both `abs` and `pow` are Python built-in's which does not need import from UFL.

I guess this goes back to the old days of UFL being wrapped directly inside DOLFIN or Firedrake, meaning that the user never interfaced with it.
