### ISSUE TITLE
ufl sphinx docs do not build

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/ufl#61]
Do the docs (doc/sphinx) for ufl need to be updated?  I suspect they're configured to an old version of sphinx. requirements.txt declares `sphinx==1.7.0`, but the sphinx version available to me at the moment is 3.4.3.

When I run `make html` from doc/sphinx, it fails with `No module named 'sphinx.apidoc'`,
```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v3.4.3
making output directory... done
WARNING: html_static_path entry '_static' does not exist

Extension error:
Handler <function run_apidoc at 0x7f8e5e7a80d0> for event 'builder-inited' threw an exception (exception: No module named 'sphinx.apidoc')
make: *** [Makefile:55: html] Error 2
```

doc/sphinx/source/conf.py uses ([l.298](https://github.com/FEniCS/ufl/blob/a7426bd8533f2c819f7f164df9c197e277d058c3/doc/sphinx/source/conf.py#L298))
```
    from sphinx.apidoc import main
```
I guess `sphinx.apidoc` must have appeared in sphinx 1.7.0, and is no longer available.  `sphinxcontrib.apidoc` is available on my system, but substituting  `sphinx.apidoc` for  `sphinxcontrib.apidoc` is not the solution (`exception: cannot import name 'main' from 'sphinxcontrib.apidoc'`)

**Comment by wence-** [comment]
I think that PR should fix things.
